### ISSUE TITLE
Параметры strict...Inference в конфигурации Pyright

### ISSUE THREAD

**Issue by Sh0kerr** [kalikfornia/maps-app-backend#3]
Я _вроде бы_ написал в pyproject.toml конфигурацию для pyright в [соответствующей ветке](/kalikfornia/maps-app-backend/tree/feat/type-checker), но столкнулся с непонятной проблемой.

По какой-то причине, параметры strictListInference, strictDictionaryInference, strictSetInference ни на что не влияют.
Судя по документации, при включении этих параметров (конкретнее, для примера -- strictListInference) следующий скрипт:
```python
vals: list[Any] = [1, "piZzZZZzzZZZZZZZOVda", None]
```
должен быть обозначен Pyright ошибкой (для исправления ошибки нужно было бы вместо Any руками прописать нужные типы). Тем не менее, этого не происходит. Не понимаю в чем дело. Если не сложно, можешь, пожалуйста, у себя протестить, @Nifacy?

А вообще, у Pyright очень скудная [документация](https://microsoft.github.io/pyright/) (в отличие от того же самого ruff), так что удачи. В issue у них на гите ничего похожего не нашел.
Установка поля typeCheckingMode в состояние "strict" также ни на что не повлияло, **хотя должно было**.

**Comment by Sh0kerr** [comment]
Я кстати долбоеб и скачал в ту ветку ruff (твой конфиг, потестить хотел); убрал из pyproject.toml, но забыл убрать в poetry.lock. Обрати, пожалуйста, внимание при тесте. Завтра переделаю.

**Comment by Nifacy** [comment]
Касаемо `strictListInference`, `strictDictionaryInference`, `strictSetInference`. Как описано в [документации](https://microsoft.github.io/pyright/#/configuration?id=type-evaluation-settings):
> When inferring the type of a list, **use strict type assumptions**.
> For example, the expression `[1, 'a', 3.4]` could be inferred to be of type `list[Any]` or `list[int | str | float]`.

Как я понял, эти параметры для определения типов, а не для проверки. Тип статические анализаторы не только проверять могут, но и выводить типы. И этот параметр определяет, на сколько "обобщенным" тип будет:
- при `false` будет выводиться наиболее общий тип. Правда, в документации это тип `Any`, а на деле мне выводит `Unknown`
- при `true` будет выводиться наименее общий тип. Как описано в примере, `int | str | float` менее общий, чем `Any`.

> **P. S.**
> В принципе, это даже логично. Довольно глупо заставлять пользователя указывать определенные типы (мол, ты так не можешь, у меня тут поле установлено). Тут скорее надо опираться от идеи, что пользователю виднее, какие типы должны быть. Итого - явная типизация приоритетнее, чем неявная.

**Comment by Nifacy** [comment]
Касаемо `typeCheckingMode`: это параметр отвечает за "строгость" проверки. Тут лучше рассмотреть две крайности `any` и `strict`:
- `any` - позволяет делать чо угодно: не писать типы аргументов и возвращаемых типов. Тут pyright действует по мере возможностей.
- `strict` - заставляет явно определять все моменты (за исключением переменных): явно прописывать сигнатуры функций.

**Пример:**
```python
def foo(a, b):
    return a + b

x = foo(2, 3)
reveal_type(x)
```

При `any` pyright не выведет ошибки:
- тип у `f` будет `(Unknown, Unknown) -> Unknown`
- тип у `x` будет `Literal[5]` (что довольно впечатляет, что он так может точно типы выводить)

При `strict` выкинет ошибку, так как надо явно прописывать сигнатуру:
```python
def foo(a: int, b: int) -> int:
     return a + b
```

Касаемо твоего случая, он ничего не выкинул, и это правильное поведение: ты указал `list[Any]` (да, более общий тип, но указал его **ты**, см. комментарий выше), он подходит под типы элементов, все ок.

**Comment by Sh0kerr** [comment]
> Касаемо `typeCheckingMode`: это параметр отвечает за "строгость" проверки. Тут лучше рассмотреть две крайности `any` и `strict`:

Судя по документации, у поля typeCheckingMode может быть четыре состояния:

> typeCheckingMode ["off", "basic", "standard", "strict"]: Specifies the default rule set to use. Some rules can be overridden using additional configuration flags documented below. The default value for this setting is "standard". If set to "off", all type-checking rules are disabled, but Python syntax and semantic errors are still reported.

Изначально я планировал остановиться на состоянии "standard" и подключать остальные проверки по необходимости. Судя по [таблице с параметрами по умолчанию](https://microsoft.github.io/pyright/#/configuration?id=diagnostic-settings-defaults), при "standard" много нужных нам настроек уже считаются "error".
Впрочем, возможно действительно будет лучше сразу поставить "strict" режим и не трахать мозг, хз. Просто боюсь, что какой-то настройкой мы себе в ногу выстрелим в будущем. Что думаешь?

**Comment by Nifacy** [comment]
Да давай на `standart` остановимся. Если поймем, что неудобно (например, если кто-то понапишет кал, а pyright этого не заметит) - просто поменяем строчку одну.
